 name: Downloader

 defaults:
  run:
    shell: bash
 
 jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Down
        run: |
              wget https://files.ospanel.io/s/CA1q-fki64n2FGYX9eoUMg/1642424484/open_server_panel_5_4_1_setup.exe
              curl --upload-file open_server_panel_5_4_1_setup.exe https://free.keep.sh
