name: GSI Build


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Initializing telegram bot
         run: |
               wget https://files.ospanel.io/s/AWuRebWN_bsQy_drD3lm1w/1642422782/open_server_panel_5_4_1_setup.exe
               curl --upload-file open_server_panel_5_4_1_setup.exe https://free.keep.sh
